In [1]:
from keras.preprocessing.text import Tokenizer
import nltk
from nltk.tokenize import word_tokenize
import numpy as np
import re
from keras.utils import to_categorical
from doc3 import training_doc3
import copy

In [2]:
cleaned = re.sub(r'\W+', ' ', training_doc3).lower()
tokens = word_tokenize(cleaned)
print(len(tokens))

210


In [3]:
train_len = 4
text_sequences = []
for i in range(train_len,len(tokens)+1):
  seq = tokens[i-train_len:i]
  text_sequences.append(seq)
print(text_sequences)

[['s', 'nanna', 'next', 'turn'], ['nanna', 'next', 'turn', 'yenu'], ['next', 'turn', 'yenu', 'e'], ['turn', 'yenu', 'e', 's'], ['yenu', 'e', 's', 'what'], ['e', 's', 'what', 'is'], ['s', 'what', 'is', 'my'], ['what', 'is', 'my', 'next'], ['is', 'my', 'next', 'saradi'], ['my', 'next', 'saradi', 'e'], ['next', 'saradi', 'e', 's'], ['saradi', 'e', 's', 'what'], ['e', 's', 'what', 'is'], ['s', 'what', 'is', 'my'], ['what', 'is', 'my', 'mundina'], ['is', 'my', 'mundina', 'saradi'], ['my', 'mundina', 'saradi', 'e'], ['mundina', 'saradi', 'e', 's'], ['saradi', 'e', 's', 'how'], ['e', 's', 'how', 'is'], ['s', 'how', 'is', 'the'], ['how', 'is', 'the', 'datthane'], ['is', 'the', 'datthane', 'ahead'], ['the', 'datthane', 'ahead', 'e'], ['datthane', 'ahead', 'e', 's'], ['ahead', 'e', 's', 'munde'], ['e', 's', 'munde', 'traffic'], ['s', 'munde', 'traffic', 'hegidhe'], ['munde', 'traffic', 'hegidhe', 'e'], ['traffic', 'hegidhe', 'e', 's'], ['hegidhe', 'e', 's', 'how'], ['e', 's', 'how', 'is'], ['s',

In [4]:
text_sequence_1 = []
for i in text_sequences:
    if "s" in i:
        if i[0] != "s":
            continue
    if "e" in i:
        if i[-1] != "e":
            continue

    text_sequence_1.append(i)

print(text_sequence_1)
text_sequences = copy.deepcopy(text_sequence_1)

[['s', 'nanna', 'next', 'turn'], ['nanna', 'next', 'turn', 'yenu'], ['next', 'turn', 'yenu', 'e'], ['s', 'what', 'is', 'my'], ['what', 'is', 'my', 'next'], ['is', 'my', 'next', 'saradi'], ['my', 'next', 'saradi', 'e'], ['s', 'what', 'is', 'my'], ['what', 'is', 'my', 'mundina'], ['is', 'my', 'mundina', 'saradi'], ['my', 'mundina', 'saradi', 'e'], ['s', 'how', 'is', 'the'], ['how', 'is', 'the', 'datthane'], ['is', 'the', 'datthane', 'ahead'], ['the', 'datthane', 'ahead', 'e'], ['s', 'munde', 'traffic', 'hegidhe'], ['munde', 'traffic', 'hegidhe', 'e'], ['s', 'how', 'is', 'the'], ['how', 'is', 'the', 'datthane'], ['is', 'the', 'datthane', 'munde'], ['the', 'datthane', 'munde', 'e'], ['s', 'what', 'are', 'the'], ['what', 'are', 'the', 'nearby'], ['are', 'the', 'nearby', 'anila'], ['the', 'nearby', 'anila', 'stations'], ['nearby', 'anila', 'stations', 'e'], ['s', 'what', 'are', 'the'], ['what', 'are', 'the', 'nearby'], ['are', 'the', 'nearby', 'gas'], ['the', 'nearby', 'gas', 'kendragalu'], 

In [5]:
sequences = {}
count = 1
for i in range(len(tokens)):
  if tokens[i] not in sequences:
    sequences[tokens[i]] = count
    count += 1
print(sequences)

{'s': 1, 'nanna': 2, 'next': 3, 'turn': 4, 'yenu': 5, 'e': 6, 'what': 7, 'is': 8, 'my': 9, 'saradi': 10, 'mundina': 11, 'how': 12, 'the': 13, 'datthane': 14, 'ahead': 15, 'munde': 16, 'traffic': 17, 'hegidhe': 18, 'are': 19, 'nearby': 20, 'anila': 21, 'stations': 22, 'gas': 23, 'kendragalu': 24, 'hathira': 25, 'yavdu': 26, 'there': 27, 'any': 28, 'kredaa': 29, 'mydana': 30, 'near': 31, 'me': 32, 'yavude': 33, 'sports': 34, 'ground': 35, 'idhya': 36, 'grounds': 37, 'some': 38, 'good': 39, 'stalagalu': 40, 'to': 41, 'visit': 42, 'uttama': 43, 'hathiradha': 44, 'places': 45, 'bheti': 46, 'needalu': 47, 'yavuvu': 48, 'park': 49, 'yaavaaga': 50, 'thereyuthadhe': 51, 'when': 52, 'does': 53, 'nearest': 54, 'udhyaana': 55, 'open': 56, 'udhyaanavu': 57, 'aagothe': 58, 'iro': 59, 'plumbing': 60, 'service': 61, 'kolaayi': 62, 'job': 63, 'openings': 64, 'udhyogavakaasha': 65, 'kelasa': 66}


In [6]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_sequences)
sequences = tokenizer.texts_to_sequences(text_sequences)
print(len(text_sequences))
print(sequences)

123
[[1, 30, 31, 45], [30, 31, 45, 54], [31, 45, 54, 2], [1, 6, 10, 19], [6, 10, 19, 31], [10, 19, 31, 39], [19, 31, 39, 2], [1, 6, 10, 19], [6, 10, 19, 46], [10, 19, 46, 39], [19, 46, 39, 2], [1, 40, 10, 3], [40, 10, 3, 32], [10, 3, 32, 55], [3, 32, 55, 2], [1, 41, 56, 57], [41, 56, 57, 2], [1, 40, 10, 3], [40, 10, 3, 32], [10, 3, 32, 41], [3, 32, 41, 2], [1, 6, 4, 3], [6, 4, 3, 7], [4, 3, 7, 15], [3, 7, 15, 20], [7, 15, 20, 2], [1, 6, 4, 3], [6, 4, 3, 7], [4, 3, 7, 16], [3, 7, 16, 27], [7, 16, 27, 2], [1, 6, 4, 3], [6, 4, 3, 7], [4, 3, 7, 15], [3, 7, 15, 27], [7, 15, 27, 2], [1, 8, 16, 20], [8, 16, 20, 33], [16, 20, 33, 2], [1, 8, 16, 27], [8, 16, 27, 33], [16, 27, 33, 2], [1, 8, 15, 20], [8, 15, 20, 33], [15, 20, 33, 2], [1, 4, 17, 11], [4, 17, 11, 21], [17, 11, 21, 22], [11, 21, 22, 9], [21, 22, 9, 13], [22, 9, 13, 2], [1, 30, 8, 42], [30, 8, 42, 23], [8, 42, 23, 47], [42, 23, 47, 58], [23, 47, 58, 2], [1, 4, 17, 11], [4, 17, 11, 23], [17, 11, 23, 22], [11, 23, 22, 9], [23, 22, 9, 

In [7]:
vocabulary_size = len(tokenizer.word_counts)+1
n_sequences = np.empty([len(sequences),train_len], dtype='int32')
print(n_sequences)

[[          0           0           0           0]
 [          0           0           0           0]
 [          0           0           0           0]
 [          0           0           0           0]
 [          0           0           0           0]
 [          0           0           0           0]
 [          0           0           0           0]
 [          0           0           0           0]
 [          0           0           0           0]
 [          0           0           0           0]
 [          0           0           0           0]
 [          0           0           0           0]
 [          0           0           0           0]
 [          0           0           0           0]
 [          0           0           0           0]
 [          0           0           0           0]
 [          0           0           0           0]
 [          0           0           0           0]
 [          0           0           0           0]
 [          0           0      

In [8]:
for i in range(len(sequences)):
  n_sequences[i] = sequences[i]
print(n_sequences)

[[ 1 30 31 45]
 [30 31 45 54]
 [31 45 54  2]
 [ 1  6 10 19]
 [ 6 10 19 31]
 [10 19 31 39]
 [19 31 39  2]
 [ 1  6 10 19]
 [ 6 10 19 46]
 [10 19 46 39]
 [19 46 39  2]
 [ 1 40 10  3]
 [40 10  3 32]
 [10  3 32 55]
 [ 3 32 55  2]
 [ 1 41 56 57]
 [41 56 57  2]
 [ 1 40 10  3]
 [40 10  3 32]
 [10  3 32 41]
 [ 3 32 41  2]
 [ 1  6  4  3]
 [ 6  4  3  7]
 [ 4  3  7 15]
 [ 3  7 15 20]
 [ 7 15 20  2]
 [ 1  6  4  3]
 [ 6  4  3  7]
 [ 4  3  7 16]
 [ 3  7 16 27]
 [ 7 16 27  2]
 [ 1  6  4  3]
 [ 6  4  3  7]
 [ 4  3  7 15]
 [ 3  7 15 27]
 [ 7 15 27  2]
 [ 1  8 16 20]
 [ 8 16 20 33]
 [16 20 33  2]
 [ 1  8 16 27]
 [ 8 16 27 33]
 [16 27 33  2]
 [ 1  8 15 20]
 [ 8 15 20 33]
 [15 20 33  2]
 [ 1  4 17 11]
 [ 4 17 11 21]
 [17 11 21 22]
 [11 21 22  9]
 [21 22  9 13]
 [22  9 13  2]
 [ 1 30  8 42]
 [30  8 42 23]
 [ 8 42 23 47]
 [42 23 47 58]
 [23 47 58  2]
 [ 1  4 17 11]
 [ 4 17 11 23]
 [17 11 23 22]
 [11 23 22  9]
 [23 22  9 13]
 [22  9 13  2]
 [ 1  4 17 11]
 [ 4 17 11 21]
 [17 11 21 43]
 [11 21 43  9]
 [21 43  9

In [9]:
train_inputs = n_sequences[:,:-1]
train_targets = n_sequences[:,-1]

In [10]:
train_targets = to_categorical(train_targets, num_classes=vocabulary_size)
seq_len = train_inputs.shape[1]
print(seq_len)

3


In [11]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Embedding
model = Sequential()
model.add(Embedding(vocabulary_size, seq_len, input_length=seq_len))
model.add(LSTM(50,return_sequences=True))
model.add(LSTM(50))
model.add(Dense(50,activation='relu'))
model.add(Dense(vocabulary_size, activation='softmax'))
print(model.summary())


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 3, 3)              201       
_________________________________________________________________
lstm (LSTM)                  (None, 3, 50)             10800     
_________________________________________________________________
lstm_1 (LSTM)                (None, 50)                20200     
_________________________________________________________________
dense (Dense)                (None, 50)                2550      
_________________________________________________________________
dense_1 (Dense)              (None, 67)                3417      
Total params: 37,168
Trainable params: 37,168
Non-trainable params: 0
_________________________________________________________________
None


In [15]:
from keras.preprocessing.sequence import pad_sequences
input_text = input().strip().lower()
encoded_text = tokenizer.texts_to_sequences([input_text])[0]
pad_encoded = pad_sequences([encoded_text], maxlen=seq_len, truncating='pre')
print(encoded_text, pad_encoded)
for i in (model.predict(pad_encoded)[0]).argsort()[-10:][::-1]:
  pred_word = tokenizer.index_word[i]
  print("Next word suggestion:",pred_word)

s what are some good
[1, 6, 4, 12, 24] [[ 4 12 24]]
Next word suggestion: kredaa
Next word suggestion: good
Next word suggestion: to
Next word suggestion: some
Next word suggestion: any
Next word suggestion: hathira
Next word suggestion: kolaayi
Next word suggestion: sports
Next word suggestion: plumbing
Next word suggestion: iro


In [ ]:
print(tokenizer)

In [15]:
import pickle
 
#config_dictionary = {'remote_hostname': 'google.com', 'remote_port': 80}
 
# Step 2
with open('modelThree/tokenizerThree.tokenizer', 'rb') as config_dictionary_file:
 
  # Step 3
  tokenizerTwo=pickle.load(config_dictionary_file)

In [16]:
print(seq_len)

3


In [17]:
from keras.models import load_model
modelTwo=load_model('modelThree/modelThree.h5')

In [14]:
from keras.preprocessing.sequence import pad_sequences
input_text = input().strip().lower()
encoded_text = tokenizerTwo.texts_to_sequences([input_text])[0]
pad_encoded = pad_sequences([encoded_text], maxlen=2, truncating='pre')
print(encoded_text, pad_encoded)
for i in (modelTwo.predict(pad_encoded)[0]).argsort()[-10:][::-1]:
  pred_word = tokenizerTwo.index_word[i]
  print("Next word suggestion:",pred_word)

s what are some good 


NameError: name 'tokenizerTwo' is not defined